# Generated by Django 4.0.5 on 2022-06-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_article_postdate_category_catcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_picture',
            field=models.FileField(default='defaultuser.png', upload_to=''),
        ),
    ]
